from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState
from langgraph.graph.message import AnyMessage, add_messages


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        dict, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        dict, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[dict, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    risky_history: Annotated[
        dict, "Risky Agent's Conversation history"
    ]  # Conversation history
    safe_history: Annotated[
        dict, "Safe Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        dict, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[dict, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[
        str, "Latest response by the risky analyst"
    ]  # Last response
    current_safe_response: Annotated[
        str, "Latest response by the safe analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Portfolio optimization state
class PortfolioOptimizationState(TypedDict):
    position_sizing: Annotated[dict, "Optimized position weights and methodology"]
    hedging_strategy: Annotated[dict, "Proposed hedging instruments and parameters"]
    beta_hedge: Annotated[dict, "Beta neutral hedge plan"]
    risk_metrics: Annotated[dict, "Risk / return metrics for the portfolio"]
    final_recommendation: Annotated[str, "Concise optimisation recommendation"]
    confidence: Annotated[str, "Confidence level (1-100)"]


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[dict, "Report from the Market Analyst"]
    sentiment_report: Annotated[dict, "Report from the Social Media Analyst"]
    news_report: Annotated[dict, "Report from the News Researcher of current world affairs"]
    fundamentals_report: Annotated[dict, "Report from the Fundamentals Researcher"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[dict, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[dict, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[dict, "Final decision made by the Risk Analysts"]

    # portfolio optimisation step
    portfolio_optimization_state: Annotated[
        PortfolioOptimizationState, "Quantitative portfolio optimisation output"
    ]
    optimized_position_sizing: Annotated[dict, "Optimised position sizing"]
    hedging_strategy: Annotated[dict, "Hedging strategy details"]
    beta_hedging_plan: Annotated[dict, "Market beta hedge implementation plan"]

    # quant options manager outputs
    quant_options_report_file: Annotated[str, "Path to Quant Options Manager markdown report"]
    quant_strategies: Annotated[dict, "Selected quantitative strategies forwarded to optimizer"]
